#!/usr/bin/env bash
# create_prs.sh - Create PRs from worktrees with changes
# Usage: create_prs.sh <target-dir> <base-branch>

set -euo pipefail

TARGET_DIR="${1:-$(git rev-parse --show-toplevel)/.claude/worktrees}"
BASE_BRANCH="${2:-main}"

echo "=== Creating PRs from Worktrees ==="

created_prs=()
skipped_prs=()

for worktree in "$TARGET_DIR"/*/; do
    [[ -d "$worktree" ]] || continue
    name=$(basename "$worktree")
    [[ "$name" == "aggregated" ]] && continue

    cd "$worktree"

    # Check for changes
    if git diff --quiet && git diff --staged --quiet; then
        echo "No changes in $name, skipping..."
        skipped_prs+=("$name")
        cd - > /dev/null
        continue
    fi

    # Read metadata
    metadata_file="$worktree/.claude/worktree-metadata.json"
    if [[ -f "$metadata_file" ]]; then
        focus=$(jq -r '.focus' "$metadata_file" 2>/dev/null || echo "unknown")
        agent_type=$(jq -r '.agent_type' "$metadata_file" 2>/dev/null || echo "unknown")
    else
        focus="review"
        agent_type="agent"
    fi

    # Get current branch
    branch=$(git branch --show-current)

    # Stage all changes
    git add -A

    # Create commit
    commit_message="$agent_type: $focus analysis and fixes

🤖 Generated by worktree-orchestrator

Co-Authored-By: Claude <noreply@anthropic.com>"

    git commit -m "$commit_message" 2>/dev/null || {
        echo "No changes to commit in $name"
        skipped_prs+=("$name")
        cd - > /dev/null
        continue
    }

    # Push branch
    git push -u origin "$branch" 2>/dev/null || {
        echo "Failed to push $branch"
        skipped_prs+=("$name")
        cd - > /dev/null
        continue
    }

    # Create PR
    pr_title="$agent_type: $focus analysis"

    # Read findings for PR body
    pr_body="## Summary
- $agent_type analysis focusing on $focus
- Generated by worktree-orchestrator

## Changes
$(git diff "$BASE_BRANCH" --stat 2>/dev/null || echo "See commit history")

## Test plan
- [ ] Review changes
- [ ] Run tests
- [ ] Verify no regressions

🤖 Generated by worktree-orchestrator"

    pr_url=$(gh pr create --title "$pr_title" --body "$pr_body" --base "$BASE_BRANCH" 2>/dev/null || echo "")

    if [[ -n "$pr_url" ]]; then
        echo "✅ Created PR for $name: $pr_url"
        created_prs+=("$name: $pr_url")
    else
        echo "⚠️  Failed to create PR for $name"
        skipped_prs+=("$name")
    fi

    cd - > /dev/null
done

echo ""
echo "=== PR Creation Summary ==="
echo "Created: ${#created_prs[@]}"
echo "Skipped: ${#skipped_prs[@]}"

for pr in "${created_prs[@]}"; do
    echo "  ✅ $pr"
done

for sk in "${skipped_prs[@]}"; do
    echo "  ⏭️  $sk"
done
